#!/bin/bash
#title:         apache.sh
#description:   Bash script to complete work sample.
#author:        Elliott Ning
#date:          20171115
#version:       1.0
#====================================================

echo "Update system..."
#yum -y update
yum -y install yum-utils

echo "Install software for webserver."
yum -y install httpd

echo "Enable firewall to have ports 80 / 443 opened; start and enable webserver."
firewall-cmd --permanent --add-port=80/tcp
firewall-cmd --permanent --add-port=443/tcp
firewall-cmd --reload

echo "Start and enable webserver."
systemctl start httpd
systemctl enable httpd

echo "download content"
cd /ebsvolume
wget https://raw.githubusercontent.com/elliottgit/demo/master/index.html
chown -R apache:apache /ebsvolume/*

#EOF
